#Application Configuration
server:
  port: 8085

# To See H2 Console in Browser:
# http://localhost:8085/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
# ===============================
# DB
# ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-clinica?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#embedded-database-connection: h2
    username: root
    password: leinad


# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
#show_sql: true
#use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

