#Application Configuration
server:
  port: 8086

# To See H2 Console in Browser:
# http://localhost:8086/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/micro_clinica
    driver-class-name: com.mysql.cj.jdbc.Driver
    #embedded-database-connection: h2
    username: root
    password: leinad
    #url: jdbc:mysql://localhost:3306/clinica_veterinaria

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    #hibernate:
      #ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        #use_sql_comments: false
        format_sql: true

  application:
    name: client_service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org:
      springframework:
        security:
          web: debug

eureka:
  client:
    eureka-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


