
#Application Configuration
server:
  port: 8087

# To See H2 Console in Browser:
# http://localhost:8087/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    #url: jdbc:mysql://localhost:3306/microservice-clinica
    driver-class-name: com.mysql.cj.jdbc.Driver
    #embedded-database-connection: h2
    username: root
    password: leinad
    url: jdbc:mysql://localhost:3306/clinica_veterinaria?createDatabaseIfNotExist=true


  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        #use_sql_comments: false
        format_sql: true

  application:
    name: consult-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    eureka-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}